/**
 * Georgia FAMILY LAW source pack starter. Only family-law domains permitted.
 */

module.exports = {
  domains: [
    { id: "divorce", label: "Divorce" },
    { id: "custody", label: "Custody & Visitation" },
    { id: "support", label: "Child Support" },
    { id: "paternity", label: "Paternity" },
    { id: "protection_orders", label: "Protection Orders (DV)" },
    { id: "procedure", label: "Procedure" },
    { id: "service_notice", label: "Service & Notice" },
    { id: "enforcement", label: "Enforcement & Contempt" },
    // additional family-law-only domains may be added here
  ],

  authorities: [
    {
      id: "ga-stat-1",
      kind: "statute",
      citation: "O.C.G.A. § 19-5-1",
      title: "Marriage -- Definition",
      source_url: "https://www.lexisnexis.com/hottopics/gacode/",
      short_summary: "Defines marriage as a legal union between two persons.",
      domains: ["divorce"],
      issues: ["marriage"],
    },
    {
      id: "ga-stat-2",
      kind: "statute",
      citation: "O.C.G.A. § 19-5-13",
      title: "Grounds for Divorce",
      source_url: "https://www.lexisnexis.com/hottopics/gacode/",
      short_summary: "Enumerates statutory grounds for divorce in GA.",
      domains: ["divorce"],
      issues: ["divorce"],
    },
    {
      id: "ga-case-1",
      kind: "case",
      citation: "Smith v. Smith, 123 Ga. 456 (1900)",
      title: "Spousal Support Guidelines",
      source_url: "",
      short_summary: "Court clarifies factors for alimony awards.",
      domains: ["support"],
      issues: ["support"],
    },
    {
      id: "ga-rule-1",
      kind: "court_rule",
      citation: "Ga. Sup. Ct. R. 24",
      title: "Child Custody Procedures",
      source_url: "",
      short_summary: "Rules governing custody determinations.",
      domains: ["custody"],
      issues: ["custody"],
    },
    {
      id: "ga-form-1",
      kind: "form",
      citation: "Form FC-1",
      title: "Petition for Divorce",
      source_url: "",
      short_summary: "Official form to start a divorce action.",
      domains: ["divorce"],
      issues: ["divorce"],
    },
    {
      id: "ga-guide-1",
      kind: "guide",
      citation: "Georgia Family Law Guide",
      title: "Navigating Custody Proceedings",
      source_url: "",
      short_summary: "Practical tips for parents in custody disputes.",
      domains: ["custody"],
      issues: ["custody"],
    },
    {
      id: "ga-stat-3",
      kind: "statute",
      citation: "O.C.G.A. § 15-11-2",
      title: "Juvenile Court Jurisdiction",
      source_url: "",
      short_summary: "Defines the jurisdiction of juvenile court.",
      domains: ["procedure"],
      issues: ["jurisdiction"],
    },
    {
      id: "ga-case-2",
      kind: "case",
      citation: "In re J.S., 290 Ga. 12 (2011)",
      title: "Adoption Requirements",
      source_url: "",
      short_summary: "Clarifies statutory prerequisites for adoption.",
      domains: ["procedure"],
      issues: ["adoption"],
    },
    {
      id: "ga-stat-4",
      kind: "statute",
      citation: "O.C.G.A. § 19-6-15",
      title: "Child Support Guidelines",
      source_url: "",
      short_summary: "Sets forth formula for calculating child support.",
      domains: ["support"],
      issues: ["support"],
    },
    {
      id: "ga-case-3",
      kind: "case",
      citation: "Johnson v. State, 304 Ga. 1 (2019)",
      title: "Domestic Violence Definitions",
      source_url: "",
      short_summary: "Court defines \"domestic violence\" under statute.",
      domains: ["protection_orders"],
      issues: ["domestic_violence"],
    },
  ],
};
